-- ⚠️ WARNING: THIS WILL DELETE ALL DATA ⚠️
-- Run this in Supabase SQL Editor to start fresh.

-- 1. Drop existing tables (Order matters due to Foreign Keys)
drop table if exists public.applications cascade;
drop table if exists public.jobs cascade;
drop table if exists public.profiles cascade;

-- 2. Recreate Profiles
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  bio text,
  phone text,
  constraint username_length check (char_length(username) >= 3)
);

-- 3. Recreate Jobs
create table public.jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  amount text,
  user_id uuid references public.profiles(id) on delete cascade not null,
  latitude float,
  longitude float,
  status text default 'OPEN',
  accepted_by uuid references public.profiles(id)
);

-- 4. Recreate Applications
create table public.applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  job_id bigint references public.jobs(id) on delete cascade not null,
  applicant_id uuid references public.profiles(id) on delete cascade not null,
  status text default 'PENDING',
  unique(job_id, applicant_id) -- Prevent duplicate applications
);

-- 5. Enable RLS
alter table public.profiles enable row level security;
alter table public.jobs enable row level security;
alter table public.applications enable row level security;

-- 6. Policies (PROFILES)
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- 7. Policies (JOBS)
create policy "Jobs are viewable by everyone." on jobs for select using (true);
create policy "Users can insert their own jobs." on jobs for insert with check (auth.uid() = user_id);
create policy "Users can update their own jobs." on jobs for update using (auth.uid() = user_id);
create policy "Users can delete their own jobs." on jobs for delete using (auth.uid() = user_id);

-- 8. Policies (APPLICATIONS)
create policy "Applicants can see own apps" on applications for select using (auth.uid() = applicant_id);
create policy "Applicants can insert own apps" on applications for insert with check (auth.uid() = applicant_id);
create policy "Job Owners can view apps for their jobs" on applications for select using (
  auth.uid() in (select user_id from jobs where id = job_id)
);
create policy "Job Owners can update apps (hire/reject)" on applications for update using (
  auth.uid() in (select user_id from jobs where id = job_id)
);

-- 9. Storage Buckets (Optional, harmless if fail)
insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true) on conflict do nothing;

drop policy if exists "Avatar images are publicly accessible." on storage.objects;
create policy "Avatar images are publicly accessible." on storage.objects for select using ( bucket_id = 'avatars' );

drop policy if exists "Anyone can upload an avatar." on storage.objects;
create policy "Anyone can upload an avatar." on storage.objects for insert with check ( bucket_id = 'avatars' );
