-- RUN THIS IN SUPABASES SQL EDITOR

-- 1. Create/Ensure Profiles Table
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  constraint username_length check (char_length(username) >= 3)
);

-- 2. Create/Ensure Jobs Table
create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  amount text,
  user_id uuid, -- We set FK later
  latitude float,
  longitude float,
  status text default 'OPEN'
);

-- 3. FIX: Explicitly add Foreign Key Constraint (Safe to run multiple times)
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'jobs_user_id_fkey') then
    alter table public.jobs 
      add constraint jobs_user_id_fkey 
      foreign key (user_id) 
      references public.profiles(id)
      on delete cascade;
  end if;
end $$;

-- 4. Enable RLS
alter table public.profiles enable row level security;
alter table public.jobs enable row level security;

-- 5. Policies for Profiles
drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

drop policy if exists "Users can update own profile." on profiles;
create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 6. Policies for Jobs
drop policy if exists "Jobs are viewable by everyone." on jobs;
create policy "Jobs are viewable by everyone."
  on jobs for select
  using ( true );

drop policy if exists "Users can insert their own jobs." on jobs;
create policy "Users can insert their own jobs."
  on jobs for insert
  with check ( auth.uid() = user_id );

drop policy if exists "Users can update their own jobs." on jobs;
create policy "Users can update their own jobs."
  on jobs for update
  using ( auth.uid() = user_id );

drop policy if exists "Users can delete their own jobs." on jobs;
create policy "Users can delete their own jobs."
  on jobs for delete
  using ( auth.uid() = user_id );

-- 7. Applications Table (if needed)
create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  job_id bigint references public.jobs(id) on delete cascade not null,
  applicant_id uuid references public.profiles(id) not null,
  status text default 'PENDING'
);

alter table public.applications enable row level security;

drop policy if exists "Applicants handles own applications" on applications;
create policy "Applicants handles own applications"
  on applications for all
  using ( auth.uid() = applicant_id );

drop policy if exists "Job Owners can view applications for their jobs" on applications;
create policy "Job Owners can view applications for their jobs"
  on applications for select
  using ( 
    auth.uid() in (
      select user_id from jobs where id = job_id
    )
  );

drop policy if exists "Job Owners can delete applications for their jobs" on applications;
create policy "Job Owners can delete applications for their jobs"
  on applications for delete
  using (
    auth.uid() in (
      select user_id from jobs where id = job_id
    )
  );
